### PR TITLE
initial support for trigger

### PR DESCRIPTION
**Pull request by csantanapr**
Closes ibm-garage-cloud/planning#283

### CODE REVIEW

**Comment by csantanapr** [comment]
@seansund I need some help with some tests that are failing
```
 FAIL  src/services/register-pipeline/register-tekton-pipeline.spec.ts
  ● register-tekton-pipeline › given registerPipeline() › when namespace exists › should get cluster type

    triggertemplates.tekton.dev "repo-name" already exists
```

**Comment by csantanapr** [comment]
The step where we fetch the git history is failign when the tekton pipeline is trigger with a git webhook, or if the git pipeline resoure `revision` instead of being a branch is a git commit sha that triggered the pipeline

For example most of our tasks have this in the first step
```bash
git fetch --unshallow
git fetch --tags
git tag -l
git checkout ${BRANCH}
```

When using ibm cloud git community it fails on the `git fetch --unshallow`
```
++ git rev-parse --abbrev-ref HEAD
+ echo 'Current branch: HEAD'
Current branch: HEAD
+ git fetch --unshallow
fatal: --unshallow on a complete repository does not make sense
```

When using github it fails on the `git checkout ${BRANCH}` in this case is a sha
```
Note: checking out 'b3bbafc8b9feff6b3fe5f4a7cd3d92f479169a95'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
  git checkout -b <new-branch-name>
HEAD is now at b3bbafc... test 1
fatal: branch 'b3bbafc8b9feff6b3fe5f4a7cd3d92f479169a95' does not exist
```

**Comment by csantanapr** [comment]
I did a lot clean up and tested on gitlab and github, the triggers are working correctly the problem now are with the tasks doing git operations with a git sha

**Comment by RamyaRaghuveera** [comment]
As the webhook tracks the push and pull requests, it passes git sha in request payload which is taken as ${BRANCH} in the git tasks. As sha is not a branch, it throws an error in tasks which have commands like git checkout ${BRANCH}, git branch --set-upstream-to=origin/${BRANCH} ${BRANCH} throw error. "git rev-parse --abbrev-ref HEAD" still gives the correct branch name. Replaced ${BRANCH} with $(git rev-parse --abbrev-ref HEAD).

**Comment by csantanapr** [comment]
> As sha is not a branch, it throws an error in tasks which have commands like git checkout ${BRANCH}, git branch --set-upstream-to=origin/${BRANCH} ${BRANCH} throw error. "git rev-parse --abbrev-ref HEAD" still gives the correct branch name. Hence,Replaced ${BRANCH} with $(git rev-parse --abbrev-ref HEAD) in task files.

Direction look ok, looking forward to see the PR for the task changes

**Pull request closed without merging**
